Update troubleshooting section
liftoffio/LiftoffAds-iOS pull request #5
Opened 2021-01-15 18:30 UTC by tao-liu-liftoff

2021-01-20 01:01 UTC, zdyn requested changes

2021-01-20 01:01 UTC, zdyn commented on README.md
> +- `"Error authentication: Check API key"`: Incorrect API key
Minor, but I'd also specify the steps they can try to resolve these, e.g.

For no API key: `Missing API key. Verify that you've included the proper initialization code (see above).`
For auth error: `Incorrect API key. Check for any typos in your API key.`

2021-01-21 15:22 UTC, tao-liu-liftoff commented on README.md
> +- `"Error authentication: Check API key"`: Incorrect API key
Ack, I took a look at prior issues. It seemed to have been caused by Mrect and Banner which use the same class. I'll remove.

2021-01-21 15:22 UTC, tao-liu-liftoff commented on README.md
> +  classes are being called (e.g. `LOBanner` for banner ads)
Ack, I took a look at prior issues. It seemed to have been caused by Mrect and Banner which use the same class. I'll remove.

2021-01-21 18:26 UTC, zdyn approved these changes

2021-01-21 20:38 UTC, merged